// Danh sách từ tiếng Hàn phổ biến - TOPIK Level 1-2 (~400 từ)
// Dùng để gợi ý từ điển offline, không cần API
export interface KoreanWord {
    korean: string;
    romanization: string;
    brief: string; // nghĩa ngắn tiếng Việt
}

export const KOREAN_WORDLIST: KoreanWord[] = [
    // Chào hỏi & giao tiếp cơ bản
    { korean: "안녕하세요", romanization: "annyeonghaseyo", brief: "xin chào" },
    { korean: "안녕", romanization: "annyeong", brief: "chào (thân mật)" },
    { korean: "감사합니다", romanization: "gamsahamnida", brief: "cảm ơn" },
    { korean: "고마워요", romanization: "gomawoyo", brief: "cảm ơn (thân mật)" },
    { korean: "죄송합니다", romanization: "joesonghamnida", brief: "xin lỗi" },
    { korean: "미안해요", romanization: "mianhaeyo", brief: "xin lỗi (thân mật)" },
    { korean: "네", romanization: "ne", brief: "vâng, có" },
    { korean: "아니요", romanization: "aniyo", brief: "không" },
    { korean: "괜찮아요", romanization: "gwaenchanayo", brief: "không sao" },
    { korean: "안녕히 가세요", romanization: "annyeonghi gaseyo", brief: "tạm biệt (người ra về)" },
    { korean: "안녕히 계세요", romanization: "annyeonghi gyeseyo", brief: "tạm biệt (người ở lại)" },
    { korean: "처음 뵙겠습니다", romanization: "cheoeum boepgesseumnida", brief: "rất vui được gặp" },
    { korean: "반갑습니다", romanization: "bangapseumnida", brief: "rất vui gặp bạn" },
    { korean: "잠깐만요", romanization: "jamkkanmanyo", brief: "chờ một chút" },
    { korean: "모르겠어요", romanization: "moreugesseoyo", brief: "tôi không biết" },
    { korean: "알겠어요", romanization: "algesseoyo", brief: "tôi hiểu rồi" },
    { korean: "부탁합니다", romanization: "butakamnida", brief: "làm ơn" },

    // Đại từ & con người
    { korean: "나", romanization: "na", brief: "tôi (thân mật)" },
    { korean: "저", romanization: "jeo", brief: "tôi (lịch sự)" },
    { korean: "너", romanization: "neo", brief: "bạn (thân mật)" },
    { korean: "당신", romanization: "dangsin", brief: "bạn (trang trọng)" },
    { korean: "우리", romanization: "uri", brief: "chúng tôi, của chúng ta" },
    { korean: "그", romanization: "geu", brief: "anh ấy, người đó" },
    { korean: "그녀", romanization: "geunyeo", brief: "cô ấy" },
    { korean: "그들", romanization: "geudeul", brief: "họ" },
    { korean: "사람", romanization: "saram", brief: "người" },
    { korean: "남자", romanization: "namja", brief: "đàn ông, con trai" },
    { korean: "여자", romanization: "yeoja", brief: "phụ nữ, con gái" },
    { korean: "아이", romanization: "ai", brief: "đứa trẻ" },
    { korean: "아기", romanization: "agi", brief: "em bé" },
    { korean: "친구", romanization: "chingu", brief: "bạn bè" },
    { korean: "가족", romanization: "gajok", brief: "gia đình" },
    { korean: "부모님", romanization: "bumonim", brief: "cha mẹ" },
    { korean: "아버지", romanization: "abeoji", brief: "cha, bố" },
    { korean: "어머니", romanization: "eomeoni", brief: "mẹ" },
    { korean: "형", romanization: "hyeong", brief: "anh (nam gọi)" },
    { korean: "오빠", romanization: "oppa", brief: "anh (nữ gọi)" },
    { korean: "누나", romanization: "nuna", brief: "chị (nam gọi)" },
    { korean: "언니", romanization: "eonni", brief: "chị (nữ gọi)" },
    { korean: "남동생", romanization: "namdongsaeng", brief: "em trai" },
    { korean: "여동생", romanization: "yeodongsaeng", brief: "em gái" },
    { korean: "할아버지", romanization: "harabeoji", brief: "ông nội/ngoại" },
    { korean: "할머니", romanization: "halmeoni", brief: "bà nội/ngoại" },
    { korean: "선생님", romanization: "seonsaengnim", brief: "thầy/cô giáo" },
    { korean: "학생", romanization: "haksaeng", brief: "học sinh" },

    // Số đếm
    { korean: "일", romanization: "il", brief: "một (Hán-Hàn)" },
    { korean: "이", romanization: "i", brief: "hai (Hán-Hàn)" },
    { korean: "삼", romanization: "sam", brief: "ba" },
    { korean: "사", romanization: "sa", brief: "bốn" },
    { korean: "오", romanization: "o", brief: "năm" },
    { korean: "육", romanization: "yuk", brief: "sáu" },
    { korean: "칠", romanization: "chil", brief: "bảy" },
    { korean: "팔", romanization: "pal", brief: "tám" },
    { korean: "구", romanization: "gu", brief: "chín" },
    { korean: "십", romanization: "sip", brief: "mười" },
    { korean: "백", romanization: "baek", brief: "một trăm" },
    { korean: "천", romanization: "cheon", brief: "một nghìn" },
    { korean: "만", romanization: "man", brief: "mười nghìn" },
    { korean: "하나", romanization: "hana", brief: "một (thuần Hàn)" },
    { korean: "둘", romanization: "dul", brief: "hai (thuần Hàn)" },
    { korean: "셋", romanization: "set", brief: "ba (thuần Hàn)" },
    { korean: "넷", romanization: "net", brief: "bốn (thuần Hàn)" },
    { korean: "다섯", romanization: "daseot", brief: "năm (thuần Hàn)" },
    { korean: "여섯", romanization: "yeoseot", brief: "sáu (thuần Hàn)" },
    { korean: "일곱", romanization: "ilgop", brief: "bảy (thuần Hàn)" },
    { korean: "여덟", romanization: "yeodeol", brief: "tám (thuần Hàn)" },
    { korean: "아홉", romanization: "ahop", brief: "chín (thuần Hàn)" },
    { korean: "열", romanization: "yeol", brief: "mười (thuần Hàn)" },

    // Thời gian
    { korean: "지금", romanization: "jigeum", brief: "bây giờ" },
    { korean: "오늘", romanization: "oneul", brief: "hôm nay" },
    { korean: "어제", romanization: "eoje", brief: "hôm qua" },
    { korean: "내일", romanization: "naeil", brief: "ngày mai" },
    { korean: "이번", romanization: "ibeon", brief: "lần này, kỳ này" },
    { korean: "다음", romanization: "daeum", brief: "tiếp theo" },
    { korean: "지난", romanization: "jinan", brief: "đã qua, trước" },
    { korean: "년", romanization: "nyeon", brief: "năm" },
    { korean: "월", romanization: "wol", brief: "tháng" },
    { korean: "일", romanization: "il", brief: "ngày" },
    { korean: "시간", romanization: "sigan", brief: "giờ, thời gian" },
    { korean: "분", romanization: "bun", brief: "phút" },
    { korean: "초", romanization: "cho", brief: "giây" },
    { korean: "아침", romanization: "achim", brief: "buổi sáng" },
    { korean: "점심", romanization: "jeomsim", brief: "buổi trưa" },
    { korean: "저녁", romanization: "jeonyeok", brief: "buổi tối" },
    { korean: "밤", romanization: "bam", brief: "đêm" },
    { korean: "주", romanization: "ju", brief: "tuần" },
    { korean: "주말", romanization: "jumal", brief: "cuối tuần" },
    { korean: "월요일", romanization: "woryoil", brief: "thứ Hai" },
    { korean: "화요일", romanization: "hwaryoil", brief: "thứ Ba" },
    { korean: "수요일", romanization: "suyoil", brief: "thứ Tư" },
    { korean: "목요일", romanization: "mogyoil", brief: "thứ Năm" },
    { korean: "금요일", romanization: "geumyoil", brief: "thứ Sáu" },
    { korean: "토요일", romanization: "toyoil", brief: "thứ Bảy" },
    { korean: "일요일", romanization: "iryoil", brief: "Chủ Nhật" },

    // Địa điểm & vị trí
    { korean: "집", romanization: "jip", brief: "nhà" },
    { korean: "학교", romanization: "hakgyo", brief: "trường học" },
    { korean: "회사", romanization: "hoesa", brief: "công ty" },
    { korean: "병원", romanization: "byeongwon", brief: "bệnh viện" },
    { korean: "식당", romanization: "sikdang", brief: "nhà hàng" },
    { korean: "카페", romanization: "kape", brief: "cà phê" },
    { korean: "마트", romanization: "mateu", brief: "siêu thị" },
    { korean: "편의점", romanization: "pyeonuijeom", brief: "cửa hàng tiện lợi" },
    { korean: "공원", romanization: "gongwon", brief: "công viên" },
    { korean: "도서관", romanization: "doseogwan", brief: "thư viện" },
    { korean: "은행", romanization: "eunhaeng", brief: "ngân hàng" },
    { korean: "공항", romanization: "gonghang", brief: "sân bay" },
    { korean: "역", romanization: "yeok", brief: "ga tàu" },
    { korean: "버스", romanization: "beoseu", brief: "xe buýt" },
    { korean: "지하철", romanization: "jihacheol", brief: "tàu điện ngầm" },
    { korean: "택시", romanization: "taeksi", brief: "taxi" },
    { korean: "나라", romanization: "nara", brief: "đất nước" },
    { korean: "도시", romanization: "dosi", brief: "thành phố" },
    { korean: "서울", romanization: "seoul", brief: "Seoul (thủ đô HQ)" },
    { korean: "한국", romanization: "hanguk", brief: "Hàn Quốc" },
    { korean: "베트남", romanization: "beteunam", brief: "Việt Nam" },
    { korean: "위", romanization: "wi", brief: "trên" },
    { korean: "아래", romanization: "arae", brief: "dưới" },
    { korean: "앞", romanization: "ap", brief: "trước" },
    { korean: "뒤", romanization: "dwi", brief: "sau" },
    { korean: "옆", romanization: "yeop", brief: "bên cạnh" },
    { korean: "안", romanization: "an", brief: "trong" },
    { korean: "밖", romanization: "bak", brief: "ngoài" },

    // Đồ ăn & uống
    { korean: "밥", romanization: "bap", brief: "cơm" },
    { korean: "물", romanization: "mul", brief: "nước" },
    { korean: "빵", romanization: "ppang", brief: "bánh mì" },
    { korean: "고기", romanization: "gogi", brief: "thịt" },
    { korean: "생선", romanization: "saengseon", brief: "cá" },
    { korean: "야채", romanization: "yachae", brief: "rau củ" },
    { korean: "과일", romanization: "gwail", brief: "trái cây" },
    { korean: "사과", romanization: "sagwa", brief: "táo" },
    { korean: "바나나", romanization: "banana", brief: "chuối" },
    { korean: "커피", romanization: "keopi", brief: "cà phê" },
    { korean: "차", romanization: "cha", brief: "trà" },
    { korean: "술", romanization: "sul", brief: "rượu, bia" },
    { korean: "김치", romanization: "gimchi", brief: "kimchi" },
    { korean: "비빔밥", romanization: "bibimbap", brief: "cơm trộn" },
    { korean: "불고기", romanization: "bulgogi", brief: "thịt nướng HQ" },
    { korean: "라면", romanization: "ramyeon", brief: "mì gói" },
    { korean: "떡", romanization: "tteok", brief: "bánh gạo" },
    { korean: "맛", romanization: "mat", brief: "vị, mùi vị" },
    { korean: "맛있다", romanization: "masitda", brief: "ngon" },
    { korean: "맵다", romanization: "maepda", brief: "cay" },
    { korean: "달다", romanization: "dalda", brief: "ngọt" },
    { korean: "짜다", romanization: "jjada", brief: "mặn" },

    // Mua sắm & tiền bạc
    { korean: "돈", romanization: "don", brief: "tiền" },
    { korean: "원", romanization: "won", brief: "won (tiền HQ)" },
    { korean: "값", romanization: "gap", brief: "giá cả" },
    { korean: "사다", romanization: "sada", brief: "mua" },
    { korean: "팔다", romanization: "palda", brief: "bán" },
    { korean: "싸다", romanization: "ssada", brief: "rẻ" },
    { korean: "비싸다", romanization: "bissada", brief: "đắt" },
    { korean: "옷", romanization: "ot", brief: "quần áo" },
    { korean: "신발", romanization: "sinbal", brief: "giày dép" },

    // Động từ phổ biến
    { korean: "가다", romanization: "gada", brief: "đi" },
    { korean: "오다", romanization: "oda", brief: "đến" },
    { korean: "있다", romanization: "itda", brief: "có, tồn tại" },
    { korean: "없다", romanization: "eopda", brief: "không có" },
    { korean: "하다", romanization: "hada", brief: "làm" },
    { korean: "먹다", romanization: "meokda", brief: "ăn" },
    { korean: "마시다", romanization: "masida", brief: "uống" },
    { korean: "보다", romanization: "boda", brief: "xem, nhìn" },
    { korean: "듣다", romanization: "deutda", brief: "nghe" },
    { korean: "말하다", romanization: "malhada", brief: "nói" },
    { korean: "읽다", romanization: "ikda", brief: "đọc" },
    { korean: "쓰다", romanization: "sseuda", brief: "viết" },
    { korean: "공부하다", romanization: "gongbuhada", brief: "học bài" },
    { korean: "일하다", romanization: "ilhada", brief: "làm việc" },
    { korean: "자다", romanization: "jada", brief: "ngủ" },
    { korean: "일어나다", romanization: "ireonada", brief: "thức dậy" },
    { korean: "앉다", romanization: "anda", brief: "ngồi" },
    { korean: "서다", romanization: "seoda", brief: "đứng" },
    { korean: "걷다", romanization: "geotda", brief: "đi bộ" },
    { korean: "뛰다", romanization: "ttwida", brief: "chạy" },
    { korean: "좋아하다", romanization: "joahada", brief: "thích" },
    { korean: "싫어하다", romanization: "sireohada", brief: "ghét" },
    { korean: "알다", romanization: "alda", brief: "biết" },
    { korean: "모르다", romanization: "moreuda", brief: "không biết" },
    { korean: "생각하다", romanization: "saenggakhada", brief: "nghĩ, suy nghĩ" },
    { korean: "원하다", romanization: "wonhada", brief: "muốn" },
    { korean: "필요하다", romanization: "pilryohada", brief: "cần" },
    { korean: "만나다", romanization: "mannada", brief: "gặp gỡ" },
    { korean: "주다", romanization: "juda", brief: "cho, tặng" },
    { korean: "받다", romanization: "batda", brief: "nhận" },
    { korean: "사랑하다", romanization: "saranghada", brief: "yêu" },
    { korean: "결혼하다", romanization: "gyeoronhada", brief: "kết hôn" },
    { korean: "시작하다", romanization: "sijakhada", brief: "bắt đầu" },
    { korean: "끝나다", romanization: "kkeunnada", brief: "kết thúc" },
    { korean: "열다", romanization: "yeolda", brief: "mở" },
    { korean: "닫다", romanization: "datda", brief: "đóng" },
    { korean: "타다", romanization: "tada", brief: "đi (xe), cưỡi" },
    { korean: "찾다", romanization: "chatda", brief: "tìm" },
    { korean: "전화하다", romanization: "jeonhwahada", brief: "gọi điện" },
    { korean: "노래하다", romanization: "noraehada", brief: "hát" },
    { korean: "춤추다", romanization: "chumchuda", brief: "nhảy múa" },

    // Tính từ phổ biến
    { korean: "크다", romanization: "keuda", brief: "to, lớn" },
    { korean: "작다", romanization: "jakda", brief: "nhỏ" },
    { korean: "많다", romanization: "manta", brief: "nhiều" },
    { korean: "적다", romanization: "jeokda", brief: "ít" },
    { korean: "좋다", romanization: "jota", brief: "tốt, hay" },
    { korean: "나쁘다", romanization: "nappeuda", brief: "xấu, tệ" },
    { korean: "빠르다", romanization: "ppareuda", brief: "nhanh" },
    { korean: "느리다", romanization: "neurida", brief: "chậm" },
    { korean: "새", romanization: "sae", brief: "mới" },
    { korean: "오래된", romanization: "oraedoen", brief: "cũ" },
    { korean: "예쁘다", romanization: "yeppeuda", brief: "đẹp" },
    { korean: "멋있다", romanization: "meositda", brief: "멋있다 (phong cách)" },
    { korean: "힘들다", romanization: "himdeulda", brief: "khó khăn, vất vả" },
    { korean: "쉽다", romanization: "swipda", brief: "dễ" },
    { korean: "어렵다", romanization: "eoryeopda", brief: "khó" },
    { korean: "재미있다", romanization: "jaemiitda", brief: "thú vị, vui" },
    { korean: "재미없다", romanization: "jaemieopda", brief: "chán" },
    { korean: "바쁘다", romanization: "bappeuda", brief: "bận rộn" },
    { korean: "피곤하다", romanization: "pigonhada", brief: "mệt mỏi" },
    { korean: "행복하다", romanization: "haengbokhada", brief: "hạnh phúc" },
    { korean: "슬프다", romanization: "seulpeuda", brief: "buồn" },
    { korean: "화나다", romanization: "hwanada", brief: "tức giận" },
    { korean: "무섭다", romanization: "museopda", brief: "đáng sợ, sợ" },
    { korean: "따뜻하다", romanization: "ttatteutada", brief: "ấm áp" },
    { korean: "춥다", romanization: "chupda", brief: "lạnh" },
    { korean: "덥다", romanization: "deobda", brief: "nóng" },
    { korean: "아프다", romanization: "apeuda", brief: "đau" },
    { korean: "건강하다", romanization: "geonganghada", brief: "khỏe mạnh" },

    // Từ thông dụng khác
    { korean: "이름", romanization: "ireum", brief: "tên" },
    { korean: "나이", romanization: "nai", brief: "tuổi" },
    { korean: "언어", romanization: "eoneo", brief: "ngôn ngữ" },
    { korean: "한국어", romanization: "hangugeo", brief: "tiếng Hàn" },
    { korean: "영어", romanization: "yeongeo", brief: "tiếng Anh" },
    { korean: "베트남어", romanization: "beteunameo", brief: "tiếng Việt" },
    { korean: "숙제", romanization: "sukje", brief: "bài tập về nhà" },
    { korean: "시험", romanization: "siheom", brief: "kỳ thi" },
    { korean: "문제", romanization: "munje", brief: "vấn đề, câu hỏi" },
    { korean: "답", romanization: "dap", brief: "câu trả lời" },
    { korean: "전화", romanization: "jeonhwa", brief: "điện thoại" },
    { korean: "컴퓨터", romanization: "keompyuteo", brief: "máy tính" },
    { korean: "인터넷", romanization: "inteonet", brief: "internet" },
    { korean: "책", romanization: "chaek", brief: "sách" },
    { korean: "영화", romanization: "yeonghwa", brief: "phim" },
    { korean: "음악", romanization: "eumak", brief: "âm nhạc" },
    { korean: "노래", romanization: "norae", brief: "bài hát" },
    { korean: "춤", romanization: "chum", brief: "điệu nhảy" },
    { korean: "스포츠", romanization: "seupocheu", brief: "thể thao" },
    { korean: "축구", romanization: "chukgu", brief: "bóng đá" },
    { korean: "날씨", romanization: "nalssi", brief: "thời tiết" },
    { korean: "비", romanization: "bi", brief: "mưa" },
    { korean: "눈", romanization: "nun", brief: "tuyết; mắt" },
    { korean: "바람", romanization: "baram", brief: "gió" },
    { korean: "하늘", romanization: "haneul", brief: "bầu trời" },
    { korean: "바다", romanization: "bada", brief: "biển" },
    { korean: "산", romanization: "san", brief: "núi" },
    { korean: "강", romanization: "gang", brief: "sông" },
    { korean: "꽃", romanization: "kkot", brief: "hoa" },
    { korean: "나무", romanization: "namu", brief: "cây" },
    { korean: "동물", romanization: "dongmul", brief: "động vật" },
    { korean: "개", romanization: "gae", brief: "con chó" },
    { korean: "고양이", romanization: "goyangi", brief: "con mèo" },
    { korean: "색", romanization: "saek", brief: "màu sắc" },
    { korean: "빨간색", romanization: "ppalgansaek", brief: "màu đỏ" },
    { korean: "파란색", romanization: "paransaek", brief: "màu xanh dương" },
    { korean: "초록색", romanization: "choroksaek", brief: "màu xanh lá" },
    { korean: "노란색", romanization: "noransaek", brief: "màu vàng" },
    { korean: "흰색", romanization: "huinsaek", brief: "màu trắng" },
    { korean: "검은색", romanization: "geomeunsaek", brief: "màu đen" },

    // Cơ thể
    { korean: "머리", romanization: "meori", brief: "đầu, tóc" },
    { korean: "얼굴", romanization: "eolgul", brief: "khuôn mặt" },
    { korean: "눈", romanization: "nun", brief: "mắt" },
    { korean: "코", romanization: "ko", brief: "mũi" },
    { korean: "입", romanization: "ip", brief: "miệng" },
    { korean: "귀", romanization: "gwi", brief: "tai" },
    { korean: "손", romanization: "son", brief: "bàn tay" },
    { korean: "발", romanization: "bal", brief: "bàn chân" },
    { korean: "다리", romanization: "dari", brief: "chân" },
    { korean: "몸", romanization: "mom", brief: "thân thể" },

    // Trạng từ & từ nối
    { korean: "매우", romanization: "maeu", brief: "rất" },
    { korean: "너무", romanization: "neomu", brief: "quá, rất" },
    { korean: "조금", romanization: "jogeum", brief: "một chút" },
    { korean: "많이", romanization: "mani", brief: "nhiều" },
    { korean: "빨리", romanization: "ppalli", brief: "nhanh lên" },
    { korean: "천천히", romanization: "cheoncheonhi", brief: "chậm thôi" },
    { korean: "항상", romanization: "hangsang", brief: "luôn luôn" },
    { korean: "자주", romanization: "jaju", brief: "thường xuyên" },
    { korean: "가끔", romanization: "gakkeum", brief: "thỉnh thoảng" },
    { korean: "절대", romanization: "jeoldae", brief: "tuyệt đối" },
    { korean: "그리고", romanization: "geurigo", brief: "và, sau đó" },
    { korean: "하지만", romanization: "hajiman", brief: "nhưng" },
    { korean: "그래서", romanization: "geuraeseo", brief: "vì vậy" },
    { korean: "또", romanization: "tto", brief: "lại, cũng" },
    { korean: "같이", romanization: "gachi", brief: "cùng nhau" },
    { korean: "혼자", romanization: "honja", brief: "một mình" },
    { korean: "왜", romanization: "wae", brief: "tại sao" },
    { korean: "어디", romanization: "eodi", brief: "ở đâu" },
    { korean: "언제", romanization: "eonje", brief: "khi nào" },
    { korean: "어떻게", romanization: "eotteoke", brief: "như thế nào" },
    { korean: "무엇", romanization: "mueot", brief: "cái gì" },
    { korean: "누구", romanization: "nugu", brief: "ai" },
    { korean: "얼마", romanization: "eolma", brief: "bao nhiêu (tiền)" },
    { korean: "몇", romanization: "myeot", brief: "mấy, bao nhiêu" },
];

/**
 * Tìm kiếm trong danh sách từ tĩnh theo prefix hoặc chứa query
 */
export function searchLocalWords(query: string, limit = 8): KoreanWord[] {
    const q = query.toLowerCase().trim();
    if (!q) return [];

    const startsWithMatches: KoreanWord[] = [];
    const containsMatches: KoreanWord[] = [];

    for (const word of KOREAN_WORDLIST) {
        if (word.korean.startsWith(q)) {
            startsWithMatches.push(word);
        } else if (word.korean.includes(q) || word.romanization.toLowerCase().includes(q) || word.brief.includes(q)) {
            containsMatches.push(word);
        }
        if (startsWithMatches.length >= limit) break;
    }

    return [...startsWithMatches, ...containsMatches].slice(0, limit);
}
